name: Check and update fallback items

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"
  workflow_dispatch:

jobs:
  update-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make code changes
      run: |
        echo "module.exports = \`$(curl -sSL https://raw.githubusercontent.com/ao-data/ao-bin-dumps/master/formatted/items.txt)\`" > src/items-fallback.js

    - name: check if needs to create PR
      id: check_changes
      run: |
        if git status --porcelain | grep -q "^.M"; then
          echo "modified=true" >> $GITHUB_ENV
          echo "Changes detected in items-fallback.js"
        else
          echo "modified=false" >> $GITHUB_ENV
          echo "No changes detected"
        fi

    - name: Create Pull Request
      if: env.modified == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        base: main
        branch: update-items-fallback
        commit-message: "feat: update items fallback"
        delete-branch: true
        title: "Update items fallback"
        body: |
          This PR updates the items fallback with the latest data from ao-bin-dumps.

          - Updated items-fallback.js with latest items data
          - Auto-generated by GitHub Actions
        token: ${{ secrets.GITHUB_TOKEN }}
